[build]
  publish = ".output/public"
  command = "npm run generate"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes (if needed)
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Required for SharedArrayBuffer and WASM multi-threading
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-origin"

# Cache static assets
[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache document scanner models
[[headers]]
  for = "/nuxt-document-scanner/models/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache onnx runtime
[[headers]]
  for = "/nuxt-document-scanner/onnx/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache opencv
[[headers]]
  for = "/nuxt-document-scanner/opencv/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
